// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (id, occurred_at, actor_id, channel, endpoint_or_event, http_method, action, error, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, occurred_at, actor_id, channel, endpoint_or_event, http_method, action, error, payload
`

type InsertAuditLogParams struct {
	ID              pgtype.UUID
	OccurredAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	Channel         string
	EndpointOrEvent string
	HttpMethod      pgtype.Text
	Action          string
	Error           pgtype.Text
	Payload         []byte
}

// INSERT is the only operation the audit_logs table permits; a trigger raises
// on UPDATE, DELETE and TRUNCATE.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ID,
		arg.OccurredAt,
		arg.ActorID,
		arg.Channel,
		arg.EndpointOrEvent,
		arg.HttpMethod,
		arg.Action,
		arg.Error,
		arg.Payload,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.ActorID,
		&i.Channel,
		&i.EndpointOrEvent,
		&i.HttpMethod,
		&i.Action,
		&i.Error,
		&i.Payload,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, occurred_at, actor_id, channel, endpoint_or_event, http_method, action, error, payload
FROM audit_logs
ORDER BY occurred_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.Channel,
			&i.EndpointOrEvent,
			&i.HttpMethod,
			&i.Action,
			&i.Error,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByActor = `-- name: ListAuditLogsByActor :many
SELECT id, occurred_at, actor_id, channel, endpoint_or_event, http_method, action, error, payload
FROM audit_logs
WHERE actor_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByActorParams struct {
	ActorID pgtype.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByActor, arg.ActorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.Channel,
			&i.EndpointOrEvent,
			&i.HttpMethod,
			&i.Action,
			&i.Error,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
