// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bets.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBetByRoundAndPlayer = `-- name: GetBetByRoundAndPlayer :one
SELECT id, round_id, player_id, choice, amount, won, payout, placed_at, settled_at
FROM bets
WHERE round_id = $1 AND player_id = $2
`

type GetBetByRoundAndPlayerParams struct {
	RoundID  pgtype.UUID
	PlayerID pgtype.UUID
}

func (q *Queries) GetBetByRoundAndPlayer(ctx context.Context, arg GetBetByRoundAndPlayerParams) (Bet, error) {
	row := q.db.QueryRow(ctx, getBetByRoundAndPlayer, arg.RoundID, arg.PlayerID)
	var i Bet
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.PlayerID,
		&i.Choice,
		&i.Amount,
		&i.Won,
		&i.Payout,
		&i.PlacedAt,
		&i.SettledAt,
	)
	return i, err
}

const insertBet = `-- name: InsertBet :one
INSERT INTO bets (id, round_id, player_id, choice, amount, placed_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, round_id, player_id, choice, amount, won, payout, placed_at, settled_at
`

type InsertBetParams struct {
	ID       pgtype.UUID
	RoundID  pgtype.UUID
	PlayerID pgtype.UUID
	Choice   string
	Amount   int64
	PlacedAt pgtype.Timestamptz
}

// The (round_id, player_id) unique constraint makes a duplicate submission
// fail here rather than in application code, which is what actually protects
// against two concurrent requests from the same player.
func (q *Queries) InsertBet(ctx context.Context, arg InsertBetParams) (Bet, error) {
	row := q.db.QueryRow(ctx, insertBet,
		arg.ID,
		arg.RoundID,
		arg.PlayerID,
		arg.Choice,
		arg.Amount,
		arg.PlacedAt,
	)
	var i Bet
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.PlayerID,
		&i.Choice,
		&i.Amount,
		&i.Won,
		&i.Payout,
		&i.PlacedAt,
		&i.SettledAt,
	)
	return i, err
}

const listBetsByPlayer = `-- name: ListBetsByPlayer :many
SELECT id, round_id, player_id, choice, amount, won, payout, placed_at, settled_at
FROM bets
WHERE player_id = $1
ORDER BY placed_at DESC
LIMIT $2 OFFSET $3
`

type ListBetsByPlayerParams struct {
	PlayerID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListBetsByPlayer(ctx context.Context, arg ListBetsByPlayerParams) ([]Bet, error) {
	rows, err := q.db.Query(ctx, listBetsByPlayer, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bet{}
	for rows.Next() {
		var i Bet
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.PlayerID,
			&i.Choice,
			&i.Amount,
			&i.Won,
			&i.Payout,
			&i.PlacedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBetsByRound = `-- name: ListBetsByRound :many
SELECT id, round_id, player_id, choice, amount, won, payout, placed_at, settled_at
FROM bets
WHERE round_id = $1
ORDER BY placed_at ASC
`

func (q *Queries) ListBetsByRound(ctx context.Context, roundID pgtype.UUID) ([]Bet, error) {
	rows, err := q.db.Query(ctx, listBetsByRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bet{}
	for rows.Next() {
		var i Bet
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.PlayerID,
			&i.Choice,
			&i.Amount,
			&i.Won,
			&i.Payout,
			&i.PlacedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settleBet = `-- name: SettleBet :one
UPDATE bets
SET won = $1,
    payout = $2,
    settled_at = $3
WHERE id = $4 AND won IS NULL
RETURNING id, round_id, player_id, choice, amount, won, payout, placed_at, settled_at
`

type SettleBetParams struct {
	Won       pgtype.Bool
	Payout    pgtype.Int8
	SettledAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) SettleBet(ctx context.Context, arg SettleBetParams) (Bet, error) {
	row := q.db.QueryRow(ctx, settleBet,
		arg.Won,
		arg.Payout,
		arg.SettledAt,
		arg.ID,
	)
	var i Bet
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.PlayerID,
		&i.Choice,
		&i.Amount,
		&i.Won,
		&i.Payout,
		&i.PlacedAt,
		&i.SettledAt,
	)
	return i, err
}
