// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID              pgtype.UUID
	OccurredAt      pgtype.Timestamptz
	ActorID         pgtype.UUID
	Channel         string
	EndpointOrEvent string
	HttpMethod      pgtype.Text
	Action          string
	Error           pgtype.Text
	Payload         []byte
}

type Bet struct {
	ID        pgtype.UUID
	RoundID   pgtype.UUID
	PlayerID  pgtype.UUID
	Choice    string
	Amount    int64
	Won       pgtype.Bool
	Payout    pgtype.Int8
	PlacedAt  pgtype.Timestamptz
	SettledAt pgtype.Timestamptz
}

type Player struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Balance      int64
	CreatedAt    pgtype.Timestamptz
}

type Room struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Status       string
	MaxRounds    int32
	MaxPlayers   int32
	CurrentRound int32
	CreatedAt    pgtype.Timestamptz
	ClosedAt     pgtype.Timestamptz
}

type RoomPlayer struct {
	RoomID   pgtype.UUID
	PlayerID pgtype.UUID
	JoinedAt pgtype.Timestamptz
}

type Round struct {
	ID              pgtype.UUID
	RoomID          pgtype.UUID
	Number          int32
	BettingOpensAt  pgtype.Timestamptz
	BettingClosesAt pgtype.Timestamptz
	Die1            pgtype.Int2
	Die2            pgtype.Int2
	Outcome         pgtype.Text
	Status          string
	CreatedAt       pgtype.Timestamptz
	SettledAt       pgtype.Timestamptz
}

type Transaction struct {
	ID        pgtype.UUID
	PlayerID  pgtype.UUID
	Type      string
	Amount    int64
	RoundID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
