// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlayerBalance = `-- name: AddPlayerBalance :one
UPDATE players
SET balance = balance + $1::bigint
WHERE id = $2
RETURNING id, email, password_hash, balance, created_at
`

type AddPlayerBalanceParams struct {
	Delta int64
	ID    pgtype.UUID
}

// Atomic relative adjustment; the CHECK constraint rejects a negative result.
func (q *Queries) AddPlayerBalance(ctx context.Context, arg AddPlayerBalanceParams) (Player, error) {
	row := q.db.QueryRow(ctx, addPlayerBalance, arg.Delta, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (id, email, password_hash, balance, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, balance, created_at
`

type CreatePlayerParams struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Balance      int64
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Balance,
		arg.CreatedAt,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerByEmail = `-- name: GetPlayerByEmail :one
SELECT id, email, password_hash, balance, created_at
FROM players
WHERE lower(email) = lower($1::text)
`

func (q *Queries) GetPlayerByEmail(ctx context.Context, email string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByEmail, email)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, email, password_hash, balance, created_at
FROM players
WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id pgtype.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerForUpdate = `-- name: GetPlayerForUpdate :one
SELECT id, email, password_hash, balance, created_at
FROM players
WHERE id = $1
FOR UPDATE
`

// Row-level lock taken before every balance mutation. Must run inside a
// transaction; serializes concurrent deposits/withdrawals/bets per player.
func (q *Queries) GetPlayerForUpdate(ctx context.Context, id pgtype.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerForUpdate, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const updatePlayerBalance = `-- name: UpdatePlayerBalance :one
UPDATE players
SET balance = $2
WHERE id = $1
RETURNING id, email, password_hash, balance, created_at
`

type UpdatePlayerBalanceParams struct {
	ID      pgtype.UUID
	Balance int64
}

func (q *Queries) UpdatePlayerBalance(ctx context.Context, arg UpdatePlayerBalanceParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayerBalance, arg.ID, arg.Balance)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}
