// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Atomic relative adjustment; the CHECK constraint rejects a negative result.
	AddPlayerBalance(ctx context.Context, arg AddPlayerBalanceParams) (Player, error)
	AddRoomPlayer(ctx context.Context, arg AddRoomPlayerParams) (RoomPlayer, error)
	CountRoomPlayers(ctx context.Context, roomID pgtype.UUID) (int32, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error)
	// "One room at a time": returns the non-closed room the player currently sits
	// in. Redis holds the fast path; this is the authoritative check.
	FindActiveRoomForPlayer(ctx context.Context, playerID pgtype.UUID) (pgtype.UUID, error)
	GetBetByRoundAndPlayer(ctx context.Context, arg GetBetByRoundAndPlayerParams) (Bet, error)
	GetCurrentRound(ctx context.Context, roomID pgtype.UUID) (Round, error)
	GetPlayerByEmail(ctx context.Context, email string) (Player, error)
	GetPlayerByID(ctx context.Context, id pgtype.UUID) (Player, error)
	// Row-level lock taken before every balance mutation. Must run inside a
	// transaction; serializes concurrent deposits/withdrawals/bets per player.
	GetPlayerForUpdate(ctx context.Context, id pgtype.UUID) (Player, error)
	GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error)
	GetRoomForUpdate(ctx context.Context, id pgtype.UUID) (Room, error)
	GetRoundByID(ctx context.Context, id pgtype.UUID) (Round, error)
	GetRoundByRoomAndNumber(ctx context.Context, arg GetRoundByRoomAndNumberParams) (Round, error)
	// INSERT is the only operation the audit_logs table permits; a trigger raises
	// on UPDATE, DELETE and TRUNCATE.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	// The (round_id, player_id) unique constraint makes a duplicate submission
	// fail here rather than in application code, which is what actually protects
	// against two concurrent requests from the same player.
	InsertBet(ctx context.Context, arg InsertBetParams) (Bet, error)
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByActor(ctx context.Context, arg ListAuditLogsByActorParams) ([]AuditLog, error)
	ListBetsByPlayer(ctx context.Context, arg ListBetsByPlayerParams) ([]Bet, error)
	ListBetsByRound(ctx context.Context, roundID pgtype.UUID) ([]Bet, error)
	ListOpenRooms(ctx context.Context, arg ListOpenRoomsParams) ([]ListOpenRoomsRow, error)
	ListRoomPlayers(ctx context.Context, roomID pgtype.UUID) ([]RoomPlayer, error)
	ListRoundsByRoom(ctx context.Context, roomID pgtype.UUID) ([]Round, error)
	ListTransactionsByPlayer(ctx context.Context, arg ListTransactionsByPlayerParams) ([]Transaction, error)
	RemoveRoomPlayer(ctx context.Context, arg RemoveRoomPlayerParams) (int64, error)
	SettleBet(ctx context.Context, arg SettleBetParams) (Bet, error)
	SettleRound(ctx context.Context, arg SettleRoundParams) (Round, error)
	// Ledger reconciliation helper: the signed sum must equal players.balance.
	SumTransactionsByPlayer(ctx context.Context, playerID pgtype.UUID) (int64, error)
	UpdatePlayerBalance(ctx context.Context, arg UpdatePlayerBalanceParams) (Player, error)
	UpdateRoomCurrentRound(ctx context.Context, arg UpdateRoomCurrentRoundParams) (Room, error)
	UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) (Room, error)
}

var _ Querier = (*Queries)(nil)
