// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomPlayer = `-- name: AddRoomPlayer :one
INSERT INTO room_players (room_id, player_id, joined_at)
VALUES ($1, $2, $3)
RETURNING room_id, player_id, joined_at
`

type AddRoomPlayerParams struct {
	RoomID   pgtype.UUID
	PlayerID pgtype.UUID
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) AddRoomPlayer(ctx context.Context, arg AddRoomPlayerParams) (RoomPlayer, error) {
	row := q.db.QueryRow(ctx, addRoomPlayer, arg.RoomID, arg.PlayerID, arg.JoinedAt)
	var i RoomPlayer
	err := row.Scan(&i.RoomID, &i.PlayerID, &i.JoinedAt)
	return i, err
}

const countRoomPlayers = `-- name: CountRoomPlayers :one
SELECT count(*)::int AS player_count
FROM room_players
WHERE room_id = $1
`

func (q *Queries) CountRoomPlayers(ctx context.Context, roomID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countRoomPlayers, roomID)
	var player_count int32
	err := row.Scan(&player_count)
	return player_count, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (id, owner_id, status, max_rounds, max_players, current_round, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, status, max_rounds, max_players, current_round, created_at, closed_at
`

type CreateRoomParams struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Status       string
	MaxRounds    int32
	MaxPlayers   int32
	CurrentRound int32
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.ID,
		arg.OwnerID,
		arg.Status,
		arg.MaxRounds,
		arg.MaxPlayers,
		arg.CurrentRound,
		arg.CreatedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Status,
		&i.MaxRounds,
		&i.MaxPlayers,
		&i.CurrentRound,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const findActiveRoomForPlayer = `-- name: FindActiveRoomForPlayer :one
SELECT r.id
FROM room_players rp
JOIN rooms r ON r.id = rp.room_id
WHERE rp.player_id = $1
  AND r.status <> 'closed'
ORDER BY rp.joined_at DESC
LIMIT 1
`

// "One room at a time": returns the non-closed room the player currently sits
// in. Redis holds the fast path; this is the authoritative check.
func (q *Queries) FindActiveRoomForPlayer(ctx context.Context, playerID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findActiveRoomForPlayer, playerID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, owner_id, status, max_rounds, max_players, current_round, created_at, closed_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Status,
		&i.MaxRounds,
		&i.MaxPlayers,
		&i.CurrentRound,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getRoomForUpdate = `-- name: GetRoomForUpdate :one
SELECT id, owner_id, status, max_rounds, max_players, current_round, created_at, closed_at
FROM rooms
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetRoomForUpdate(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomForUpdate, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Status,
		&i.MaxRounds,
		&i.MaxPlayers,
		&i.CurrentRound,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listOpenRooms = `-- name: ListOpenRooms :many
SELECT r.id,
       r.owner_id,
       r.status,
       r.max_rounds,
       r.max_players,
       r.current_round,
       r.created_at,
       (SELECT count(*) FROM room_players rp WHERE rp.room_id = r.id)::int AS player_count
FROM rooms r
WHERE r.status = 'open'
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListOpenRoomsParams struct {
	Limit  int32
	Offset int32
}

type ListOpenRoomsRow struct {
	ID           pgtype.UUID
	OwnerID      pgtype.UUID
	Status       string
	MaxRounds    int32
	MaxPlayers   int32
	CurrentRound int32
	CreatedAt    pgtype.Timestamptz
	PlayerCount  int32
}

func (q *Queries) ListOpenRooms(ctx context.Context, arg ListOpenRoomsParams) ([]ListOpenRoomsRow, error) {
	rows, err := q.db.Query(ctx, listOpenRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenRoomsRow{}
	for rows.Next() {
		var i ListOpenRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Status,
			&i.MaxRounds,
			&i.MaxPlayers,
			&i.CurrentRound,
			&i.CreatedAt,
			&i.PlayerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomPlayers = `-- name: ListRoomPlayers :many
SELECT room_id, player_id, joined_at
FROM room_players
WHERE room_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListRoomPlayers(ctx context.Context, roomID pgtype.UUID) ([]RoomPlayer, error) {
	rows, err := q.db.Query(ctx, listRoomPlayers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomPlayer{}
	for rows.Next() {
		var i RoomPlayer
		if err := rows.Scan(&i.RoomID, &i.PlayerID, &i.JoinedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoomPlayer = `-- name: RemoveRoomPlayer :execrows
DELETE FROM room_players
WHERE room_id = $1 AND player_id = $2
`

type RemoveRoomPlayerParams struct {
	RoomID   pgtype.UUID
	PlayerID pgtype.UUID
}

func (q *Queries) RemoveRoomPlayer(ctx context.Context, arg RemoveRoomPlayerParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeRoomPlayer, arg.RoomID, arg.PlayerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRoomCurrentRound = `-- name: UpdateRoomCurrentRound :one
UPDATE rooms
SET current_round = $2
WHERE id = $1
RETURNING id, owner_id, status, max_rounds, max_players, current_round, created_at, closed_at
`

type UpdateRoomCurrentRoundParams struct {
	ID           pgtype.UUID
	CurrentRound int32
}

func (q *Queries) UpdateRoomCurrentRound(ctx context.Context, arg UpdateRoomCurrentRoundParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomCurrentRound, arg.ID, arg.CurrentRound)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Status,
		&i.MaxRounds,
		&i.MaxPlayers,
		&i.CurrentRound,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const updateRoomStatus = `-- name: UpdateRoomStatus :one
UPDATE rooms
SET status = $1,
    closed_at = $2
WHERE id = $3
RETURNING id, owner_id, status, max_rounds, max_players, current_round, created_at, closed_at
`

type UpdateRoomStatusParams struct {
	Status   string
	ClosedAt pgtype.Timestamptz
	ID       pgtype.UUID
}

func (q *Queries) UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoomStatus, arg.Status, arg.ClosedAt, arg.ID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Status,
		&i.MaxRounds,
		&i.MaxPlayers,
		&i.CurrentRound,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}
