// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rounds.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (id, room_id, number, betting_opens_at, betting_closes_at, status)
VALUES ($1, $2, $3, $4, $5, 'betting')
RETURNING id, room_id, number, betting_opens_at, betting_closes_at, die1, die2, outcome, status, created_at, settled_at
`

type CreateRoundParams struct {
	ID              pgtype.UUID
	RoomID          pgtype.UUID
	Number          int32
	BettingOpensAt  pgtype.Timestamptz
	BettingClosesAt pgtype.Timestamptz
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRow(ctx, createRound,
		arg.ID,
		arg.RoomID,
		arg.Number,
		arg.BettingOpensAt,
		arg.BettingClosesAt,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Number,
		&i.BettingOpensAt,
		&i.BettingClosesAt,
		&i.Die1,
		&i.Die2,
		&i.Outcome,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getCurrentRound = `-- name: GetCurrentRound :one
SELECT id, room_id, number, betting_opens_at, betting_closes_at, die1, die2, outcome, status, created_at, settled_at
FROM rounds
WHERE room_id = $1
ORDER BY number DESC
LIMIT 1
`

func (q *Queries) GetCurrentRound(ctx context.Context, roomID pgtype.UUID) (Round, error) {
	row := q.db.QueryRow(ctx, getCurrentRound, roomID)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Number,
		&i.BettingOpensAt,
		&i.BettingClosesAt,
		&i.Die1,
		&i.Die2,
		&i.Outcome,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getRoundByID = `-- name: GetRoundByID :one
SELECT id, room_id, number, betting_opens_at, betting_closes_at, die1, die2, outcome, status, created_at, settled_at
FROM rounds
WHERE id = $1
`

func (q *Queries) GetRoundByID(ctx context.Context, id pgtype.UUID) (Round, error) {
	row := q.db.QueryRow(ctx, getRoundByID, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Number,
		&i.BettingOpensAt,
		&i.BettingClosesAt,
		&i.Die1,
		&i.Die2,
		&i.Outcome,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getRoundByRoomAndNumber = `-- name: GetRoundByRoomAndNumber :one
SELECT id, room_id, number, betting_opens_at, betting_closes_at, die1, die2, outcome, status, created_at, settled_at
FROM rounds
WHERE room_id = $1 AND number = $2
`

type GetRoundByRoomAndNumberParams struct {
	RoomID pgtype.UUID
	Number int32
}

func (q *Queries) GetRoundByRoomAndNumber(ctx context.Context, arg GetRoundByRoomAndNumberParams) (Round, error) {
	row := q.db.QueryRow(ctx, getRoundByRoomAndNumber, arg.RoomID, arg.Number)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Number,
		&i.BettingOpensAt,
		&i.BettingClosesAt,
		&i.Die1,
		&i.Die2,
		&i.Outcome,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const listRoundsByRoom = `-- name: ListRoundsByRoom :many
SELECT id, room_id, number, betting_opens_at, betting_closes_at, die1, die2, outcome, status, created_at, settled_at
FROM rounds
WHERE room_id = $1
ORDER BY number ASC
`

func (q *Queries) ListRoundsByRoom(ctx context.Context, roomID pgtype.UUID) ([]Round, error) {
	rows, err := q.db.Query(ctx, listRoundsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Round{}
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Number,
			&i.BettingOpensAt,
			&i.BettingClosesAt,
			&i.Die1,
			&i.Die2,
			&i.Outcome,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settleRound = `-- name: SettleRound :one
UPDATE rounds
SET die1 = $1,
    die2 = $2,
    outcome = $3,
    status = 'settled',
    settled_at = $4
WHERE id = $5 AND status = 'betting'
RETURNING id, room_id, number, betting_opens_at, betting_closes_at, die1, die2, outcome, status, created_at, settled_at
`

type SettleRoundParams struct {
	Die1      pgtype.Int2
	Die2      pgtype.Int2
	Outcome   pgtype.Text
	SettledAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) SettleRound(ctx context.Context, arg SettleRoundParams) (Round, error) {
	row := q.db.QueryRow(ctx, settleRound,
		arg.Die1,
		arg.Die2,
		arg.Outcome,
		arg.SettledAt,
		arg.ID,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Number,
		&i.BettingOpensAt,
		&i.BettingClosesAt,
		&i.Die1,
		&i.Die2,
		&i.Outcome,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}
