// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (id, player_id, type, amount, round_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, player_id, type, amount, round_id, created_at
`

type InsertTransactionParams struct {
	ID        pgtype.UUID
	PlayerID  pgtype.UUID
	Type      string
	Amount    int64
	RoundID   pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.ID,
		arg.PlayerID,
		arg.Type,
		arg.Amount,
		arg.RoundID,
		arg.CreatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Type,
		&i.Amount,
		&i.RoundID,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionsByPlayer = `-- name: ListTransactionsByPlayer :many
SELECT id, player_id, type, amount, round_id, created_at
FROM transactions
WHERE player_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByPlayerParams struct {
	PlayerID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListTransactionsByPlayer(ctx context.Context, arg ListTransactionsByPlayerParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByPlayer, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.Type,
			&i.Amount,
			&i.RoundID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTransactionsByPlayer = `-- name: SumTransactionsByPlayer :one
SELECT COALESCE(SUM(
    CASE
        WHEN type IN ('deposit', 'payout') THEN amount
        ELSE -amount
    END
), 0)::bigint AS net
FROM transactions
WHERE player_id = $1
`

// Ledger reconciliation helper: the signed sum must equal players.balance.
func (q *Queries) SumTransactionsByPlayer(ctx context.Context, playerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumTransactionsByPlayer, playerID)
	var net int64
	err := row.Scan(&net)
	return net, err
}
